### ISSUE TITLE
Spam virtex

### ISSUE THREAD

**Issue by DarknetJMBLO** [MR-X-junior/Virtex#4]
Min? btw pas gua ketik di termux-setup-storage normal setelah itu kan gua ketik cd Virtex itu masih bisa nah pas ls juga bisa nih nah disini ini yg sedikit janggal
Pas gua ketik python3 Virtex.py
Gabisa sama sekali adanya tulisan kaya gini $python3 Virtex.py
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/requests/
Could not fetch URL https://pypi.org/simple/requests/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement requests (from versions: none)
ERROR: No matching distribution found for requests
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.
pTraceback (most recent call last):
  File "/data/data/com.termux/files/home/Virtex/Virtex/Virtex.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
$ python2 virtex.py
The program python2 is not installed. Install it by executing:
 pkg install python2
$ png virtex.py
No command png found, did you mean:
 Command ping in package termux-tools
$
Tolong kasih sarang min agar bisa digunakan 
Terimakasih

**Comment by DarknetJMBLO** [comment]
Maaf min tadi salah ketik seharusnya saran bukan sarang

**Comment by MR-X-junior** [comment]
Maaf baru balas bang, soal nya banyak kesibukan.

Coba masukkan command :

```
$ pkg install openssl

$ pip3 install requests
```
